### ISSUE TITLE
Warning: ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'

### ISSUE THREAD

**Issue by hernancasillas** [sbycrosz/react-native-credit-card-input#224]
Hello , I'm using Expo SDK 45 and I am getting a new warning.

at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
at node_modules\react-native\index.js:470:4 in module.exports.get__ViewPropTypes
at node_modules\react-native-credit-card-input\src\CCInput.js:28:20 in CCInput
at node_modules\metro-runtime\src\polyfills\require.js:339:11 in loadModuleImplementation
at node_modules\react-native-credit-card-input\src\CreditCardInput.js:15:0 in <global>
at node_modules\metro-runtime\src\polyfills\require.js:339:11 in loadModuleImplementation
at node_modules\react-native-credit-card-input\src\index.js:2:0 in <global>
at node_modules\metro-runtime\src\polyfills\require.js:339:11 in loadModuleImplementation
at node_modules\react-native-credit-card-input\index.js:1:0 in <global>

I hope this package can get an update, it's very useful.

**Comment by hernancasillas** [comment]
Update: ViewPropTypes has been removed from React Native

Using Expo SDK 46. React Native 18
